"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const test_1 = require("@playwright/test");
const promises_1 = __importDefault(require("fs/promises"));
const os_1 = __importDefault(require("os"));
const path_1 = __importDefault(require("path"));
const scorekeeper_page_1 = require("./helpers/scorekeeper-page");
test_1.test.describe('Database JSON (.scrkpr)', () => {
    test_1.test.beforeEach(async ({ page }) => {
        await (0, scorekeeper_page_1.clearScorekeeperStorage)(page);
    });
    (0, test_1.test)('exports JSON and reload preserves teams, players, and matches', async ({ page, }) => {
        await (0, scorekeeper_page_1.gotoScorekeeper)(page);
        await (0, scorekeeper_page_1.addTeam)(page, 'Big Dogs');
        await (0, scorekeeper_page_1.openTeam)(page, 'Big Dogs');
        await (0, scorekeeper_page_1.addPlayer)(page, 'Alice');
        await (0, scorekeeper_page_1.addTeam)(page, 'Quick Cats');
        await (0, scorekeeper_page_1.openTeam)(page, 'Quick Cats');
        await (0, scorekeeper_page_1.addPlayer)(page, 'Bob');
        await (0, scorekeeper_page_1.createMatch)(page, 'Big Dogs', 'Quick Cats');
        const downloadPromise = page.waitForEvent('download');
        await (0, scorekeeper_page_1.navigateMenu)(page, 'Overview');
        await page.getByRole('button', { name: 'Download Database' }).click();
        const download = await downloadPromise;
        (0, test_1.expect)(download.suggestedFilename()).toBe('Dodgeball Database.scrkpr');
        const tempDir = await promises_1.default.mkdtemp(path_1.default.join(os_1.default.tmpdir(), 'scrkpr-'));
        const filePath = path_1.default.join(tempDir, 'database.scrkpr');
        await download.saveAs(filePath);
        const raw = await promises_1.default.readFile(filePath, 'utf-8');
        const parsed = JSON.parse(raw);
        (0, test_1.expect)(parsed).toBeTruthy();
        (0, test_1.expect)(JSON.stringify(parsed)).toContain('Big Dogs');
        (0, test_1.expect)(JSON.stringify(parsed)).toContain('Alice');
        await page.evaluate(() => sessionStorage.clear());
        await (0, scorekeeper_page_1.gotoScorekeeper)(page);
        await (0, scorekeeper_page_1.navigateMenu)(page, 'Teams');
        await (0, test_1.expect)(page.getByRole('button', { name: 'Big Dogs' })).toHaveCount(0);
        await (0, scorekeeper_page_1.navigateMenu)(page, 'Overview');
        await page.getByRole('button', { name: 'Load from file', exact: true }).click();
        await (0, scorekeeper_page_1.fileInputForExtension)(page, '.scrkpr').setInputFiles(filePath);
        await (0, scorekeeper_page_1.navigateMenu)(page, 'Teams');
        await (0, test_1.expect)(page.getByRole('button', { name: 'Big Dogs' })).toBeVisible();
        await (0, test_1.expect)(page.getByRole('button', { name: 'Quick Cats' })).toBeVisible();
        await (0, scorekeeper_page_1.openTeam)(page, 'Big Dogs');
        await (0, test_1.expect)(page.getByRole('button', { name: 'Alice' })).toBeVisible();
        await (0, scorekeeper_page_1.navigateMenu)(page, 'Matches');
        await (0, test_1.expect)(page.getByRole('button', { name: 'Big Dogs vs. Quick Cats' })).toBeVisible();
    });
});
