"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const test_1 = require("@playwright/test");
const scorekeeper_page_1 = require("./helpers/scorekeeper-page");
/** End-to-end roster and game tracking. */
test_1.test.describe('Game tracking (full roster)', () => {
    (0, test_1.test)('selects roster, adds game, opens game events', async ({ page }) => {
        await (0, scorekeeper_page_1.clearScorekeeperStorage)(page);
        await (0, scorekeeper_page_1.gotoScorekeeper)(page);
        await (0, scorekeeper_page_1.addTeam)(page, 'Home Hawks');
        await (0, scorekeeper_page_1.openTeam)(page, 'Home Hawks');
        await (0, scorekeeper_page_1.addPlayer)(page, 'H1');
        await (0, scorekeeper_page_1.addTeam)(page, 'Away Owls');
        await (0, scorekeeper_page_1.openTeam)(page, 'Away Owls');
        await (0, scorekeeper_page_1.addPlayer)(page, 'A1');
        await (0, scorekeeper_page_1.createMatch)(page, 'Home Hawks', 'Away Owls');
        await (0, scorekeeper_page_1.selectMatchRoster)(page, 'H1', 'A1');
        await (0, scorekeeper_page_1.addGame)(page);
        await (0, scorekeeper_page_1.selectGameRoster)(page, 'H1', 'A1');
        await page.getByRole('button', { name: 'Track Game' }).click();
        await (0, test_1.expect)(page.getByRole('button', { name: 'Throw', exact: true })).toBeVisible();
        await page.locator('.sk-menu-link').filter({ hasText: 'Overview' }).first().click();
        await (0, test_1.expect)(page.getByRole('heading', { name: 'Overview' })).toBeVisible();
        const resume = page.locator('.sk-resume-scoring').first();
        await (0, test_1.expect)(resume).toContainText('Resume Game 1');
        await resume.click();
        await (0, test_1.expect)(page.getByRole('button', { name: 'Throw', exact: true })).toBeVisible();
        await page.getByRole('button', { name: 'Finish', exact: true }).click();
        await page.getByRole('button', { name: 'Home Hawks', exact: true }).click();
        await (0, test_1.expect)(page.getByRole('button', { name: 'Done' })).toBeVisible();
        await page.getByRole('button', { name: 'Done' }).click();
        await (0, test_1.expect)(page.getByText('Game Complete!')).toBeVisible();
        await page.locator('.sk-menu-link').filter({ hasText: 'Overview' }).first().click();
        await (0, test_1.expect)(page.getByRole('heading', { name: 'Overview' })).toBeVisible();
        const resumeMatch = page.locator('.sk-resume-scoring').first();
        await (0, test_1.expect)(resumeMatch).toContainText('Resume match');
        await resumeMatch.click();
        await (0, test_1.expect)(page.getByRole('heading', { name: 'Track Match' })).toBeVisible();
        await (0, test_1.expect)(page.getByRole('button', { name: 'Add Game' })).toBeVisible();
    });
});
